# Production environment overrides
image:
  tag: "stable"  # Use stable tag for production
  pullPolicy: IfNotPresent

ingress:
  annotations:
    cloudflare-tunnel.ingress.kubernetes.io/tunnel-name: webserver-production
  hosts:
    - host: mclaurinquist.com
      paths:
        - path: /
          pathType: Prefix

replicaCount: 3

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
