{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    {{- include "webserver.labels" . | nindent 4 }}
{{- end }}
---
{{- range .Values.additionalNamespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ . }}
  labels:
    managed-by: {{ $.Release.Name }}
---
{{- end }}
