name: 'Terraform Plan'

on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-*.yml'

permissions:
  contents: read
  pull-requests: write
  id-token: write

env:
  TF_VERSION: '1.6.0'
  OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
  OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
  OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
  OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
  OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
  # These environment variables are no longer needed - using terraform.tfvars instead

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Setup OCI CLI
        run: |
          # Install OCI CLI
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh > install.sh
          chmod +x install.sh
          ./install.sh --accept-all-defaults
          rm install.sh
          
          # Configure OCI CLI using absolute paths
          mkdir -p /home/runner/.oci
          echo "${{ secrets.OCI_CLI_KEY_CONTENT }}" > /home/runner/.oci/oci_api_key.pem
          chmod 600 /home/runner/.oci/oci_api_key.pem
          
          cat > /home/runner/.oci/config << EOF
          [DEFAULT]
          user=${{ secrets.OCI_CLI_USER }}
          fingerprint=${{ secrets.OCI_CLI_FINGERPRINT }}
          tenancy=${{ secrets.OCI_CLI_TENANCY }}
          region=${{ secrets.OCI_CLI_REGION }}
          key_file=/home/runner/.oci/oci_api_key.pem
          EOF
          
          chmod 600 /home/runner/.oci/config

      - name: Create terraform.tfvars
        working-directory: terraform/environments/${{ matrix.environment }}
        run: |
          # Create terraform.tfvars with private key path
          cat > terraform.tfvars << EOF
          # OCI Provider Configuration
          tenancy_ocid       = "${{ secrets.OCI_CLI_TENANCY }}"
          user_ocid          = "${{ secrets.OCI_CLI_USER }}"
          fingerprint        = "${{ secrets.OCI_CLI_FINGERPRINT }}"
          private_key_path   = "/home/runner/.oci/oci_api_key.pem"
          region             = "${{ secrets.OCI_CLI_REGION }}"
          EOF
          
          # Add infrastructure configuration
          cat >> terraform.tfvars << EOF
          # Infrastructure Configuration
          compartment_id      = "${{ secrets.OCI_COMPARTMENT_ID }}"
          availability_domain = "${{ secrets.OCI_AVAILABILITY_DOMAIN }}"
          subnet_id          = "${{ secrets.OCI_PRIVATE_SUBNET }}"
          vcn_id             = "${{ secrets.OCI_VCN_ID }}"
          image_id           = "${{ secrets.OCI_CUSTOM_IMAGE }}"
          ssh_public_key     = "${{ secrets.SSH_PUBLIC_KEY }}"
          tailscale_auth_key = "${{ secrets.TAILSCALE_AUTH_KEY }}"
          EOF

      - name: Terraform Format Check
        working-directory: terraform/environments/${{ matrix.environment }}
        run: terraform fmt -check -recursive

      - name: Configure OCI Object Storage Backend
        working-directory: terraform/environments/${{ matrix.environment }}
        run: |
          # Configure HTTP backend for OCI Object Storage
          # This uses OCI Object Storage REST API directly, avoiding AWS-specific logic
          BUCKET_NAME="terraform-state-${{ matrix.environment }}"
          OBJECT_NAME="k0s-cluster/terraform.tfstate"
          BASE_URL="https://${{ secrets.OCI_NAMESPACE }}.objectstorage.${{ secrets.OCI_CLI_REGION }}.oraclecloud.com"
          
          # Set HTTP backend environment variables
          export TF_HTTP_ADDRESS="${BASE_URL}/n/${{ secrets.OCI_NAMESPACE }}/b/${BUCKET_NAME}/o/${OBJECT_NAME}"
          export TF_HTTP_LOCK_ADDRESS="${BASE_URL}/n/${{ secrets.OCI_NAMESPACE }}/b/${BUCKET_NAME}/o/${OBJECT_NAME}.lock"
          export TF_HTTP_UNLOCK_ADDRESS="${BASE_URL}/n/${{ secrets.OCI_NAMESPACE }}/b/${BUCKET_NAME}/o/${OBJECT_NAME}.lock"
          export TF_HTTP_USERNAME="${{ secrets.OCI_S3_ACCESS_KEY }}"
          export TF_HTTP_PASSWORD="${{ secrets.OCI_S3_SECRET_KEY }}"
          
          echo "Backend configuration:"
          echo "Address: $TF_HTTP_ADDRESS"
          echo "Username: ${TF_HTTP_USERNAME:0:8}..."
          
          # Export for subsequent steps
          echo "TF_HTTP_ADDRESS=$TF_HTTP_ADDRESS" >> $GITHUB_ENV
          echo "TF_HTTP_LOCK_ADDRESS=$TF_HTTP_LOCK_ADDRESS" >> $GITHUB_ENV
          echo "TF_HTTP_UNLOCK_ADDRESS=$TF_HTTP_UNLOCK_ADDRESS" >> $GITHUB_ENV
          echo "TF_HTTP_USERNAME=$TF_HTTP_USERNAME" >> $GITHUB_ENV
          echo "TF_HTTP_PASSWORD=$TF_HTTP_PASSWORD" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: terraform/environments/${{ matrix.environment }}
        run: terraform init

      - name: Terraform Validate
        working-directory: terraform/environments/${{ matrix.environment }}
        run: terraform validate

      - name: Terraform Plan
        working-directory: terraform/environments/${{ matrix.environment }}
        id: plan
        run: |
          terraform plan -no-color -out=tfplan
          terraform show -no-color tfplan > plan_output.txt

      - name: Comment Plan on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            const planOutput = fs.readFileSync(
              path.join('terraform/environments/${{ matrix.environment }}/plan_output.txt'), 
              'utf8'
            );
            
            const maxLength = 65000; // GitHub comment limit
            const truncatedOutput = planOutput.length > maxLength 
              ? planOutput.substring(0, maxLength) + '\n\n... (truncated)'
              : planOutput;

            const output = `## Terraform Plan - ${{ matrix.environment }}
            
            <details>
            <summary>Show Plan</summary>
            
            \`\`\`terraform
            ${truncatedOutput}
            \`\`\`
            
            </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            });

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan-${{ matrix.environment }}
          path: terraform/environments/${{ matrix.environment }}/tfplan
          retention-days: 5
